### PR TITLE
Live data functionality

### PR DESCRIPTION
**Pull request by omarkilani**

### CODE REVIEW

**Comment by omarkilani** [comment]
Hey @furkanksl 

I think this can be improved by storing the clients mapped to the subscribed collection ID/slug in a `sync.Map`, then on server message, only sending the message to the matching clients.

Have to be mindful of removing the clients from the `sync.Map`, something like this:

```
type CollectionClient struct {
	Client *WsClient
	CollectionID string
	Disconnect func()
}

func newClient(conn *websocket.Conn, wsServer *WsServer, disconnect func()) *WsClient {
	client := &WsClient{
		conn:     conn,
		wsServer: wsServer,
		send:     make(chan []byte),
	}

	// Set the disconnect function
	client.disconnect = func() {
		disconnect()

		if client.send != nil {
			close(client.send)
		}

		client.wsServer.unregister <- client
		client.conn.Close()
	}

	return client
}

func removeClient(collectionID string, client *WsClient) {
	value, ok := clientsMap.Load(collectionID)
	if !ok {
		return
	}

	clients := value.([]*CollectionClient)
	for i, c := range clients {
		if c.Client == client {
			clients = append(clients[:i], clients[i+1:]...)
			break
		}
	}

	if len(clients) > 0 {
		clientsMap.Store(collectionID, clients)
	} else {
		clientsMap.Delete(collectionID)
	}
}

func (ctrl Collection) GetWs(wsServer *WsServer, c *gin.Context) {
	// ...

	client := newClient(conn, wsServer, func() {
		removeClient(params.CollectionID, client)
	})

	collectionClient := &CollectionClient{
		Client: client,
		CollectionID: params.CollectionID,
		Disconnect: client.disconnect,
	}

	value, ok := clientsMap.LoadOrStore(collectionClient.CollectionID, []*CollectionClient{collectionClient})
	if ok {
		clientsMap.Store(collectionClient.CollectionID, append(value.([]*CollectionClient), collectionClient))
	}

	...

	wsServer.register <- client
}
```

**Comment by omarkilani** [comment]
@furkanksl we also need to implement reconnection logic for Ably, so if the connection drops, it's automatically reconnected.

**Comment by furkanksl** [comment]
> 

As I understand it, the purpose of making this improvement is to avoid creating a web socket with the same collection id that was created before. Right? In this way, we will prevent the unnecessary use of more resources than we need. Am I right? 🤔

**Comment by furkanksl** [comment]
> Hey @furkanksl
> 
> I think this can be improved by storing the clients mapped to the subscribed collection ID/slug in a `sync.Map`, then on server message, only sending the message to the matching clients.
> 
> Have to be mindful of removing the clients from the `sync.Map`, something like this:
> 
> ```
> type CollectionClient struct {
> 	Client *WsClient
> 	CollectionID string
> 	Disconnect func()
> }
> 
> func newClient(conn *websocket.Conn, wsServer *WsServer, disconnect func()) *WsClient {
> 	client := &WsClient{
> 		conn:     conn,
> 		wsServer: wsServer,
> 		send:     make(chan []byte),
> 	}
> 
> 	// Set the disconnect function
> 	client.disconnect = func() {
> 		disconnect()
> 
> 		if client.send != nil {
> 			close(client.send)
> 		}
> 
> 		client.wsServer.unregister <- client
> 		client.conn.Close()
> 	}
> 
> 	return client
> }
> 
> func removeClient(collectionID string, client *WsClient) {
> 	value, ok := clientsMap.Load(collectionID)
> 	if !ok {
> 		return
> 	}
> 
> 	clients := value.([]*CollectionClient)
> 	for i, c := range clients {
> 		if c.Client == client {
> 			clients = append(clients[:i], clients[i+1:]...)
> 			break
> 		}
> 	}
> 
> 	if len(clients) > 0 {
> 		clientsMap.Store(collectionID, clients)
> 	} else {
> 		clientsMap.Delete(collectionID)
> 	}
> }
> 
> func (ctrl Collection) GetWs(wsServer *WsServer, c *gin.Context) {
> 	// ...
> 
> 	client := newClient(conn, wsServer, func() {
> 		removeClient(params.CollectionID, client)
> 	})
> 
> 	collectionClient := &CollectionClient{
> 		Client: client,
> 		CollectionID: params.CollectionID,
> 		Disconnect: client.disconnect,
> 	}
> 
> 	value, ok := clientsMap.LoadOrStore(collectionClient.CollectionID, []*CollectionClient{collectionClient})
> 	if ok {
> 		clientsMap.Store(collectionClient.CollectionID, append(value.([]*CollectionClient), collectionClient))
> 	}
> 
> 	...
> 
> 	wsServer.register <- client
> }
> ```


As I understand it, the purpose of making this improvement is to avoid creating a web socket with the same collection id that was created before. Right? In this way, we will prevent the unnecessary use of more resources than we need. Am I right? 🤔

**Comment by furkanksl** [comment]
I added sync.Map into websocket. Could you check it @omarkilani ?  It definitely need a second look I guess.

**Review by metalgear-dev — APPROVED** [review]

**Review by furkanksl — APPROVED** [review]

**Pull request merged**
